DROP TABLE TEAM5_EMPLOYEES CASCADE CONSTRAINTS PURGE;
CREATE TABLE TEAM5_EMPLOYEES
(
    EMPLOYEE_ID INT NOT NULL,
    DOB         DATE,
    SALARY      INT,
    SKILLSET    VARCHAR(32),
    PRIMARY KEY (EMPLOYEE_ID)
);

grant all on "CAM13052".TEAM5_EMPLOYEES to "ETG16101","SES14019","PRT15101" with grant option;

DROP TABLE TEAM5_CUSTOMER CASCADE CONSTRAINTS PURGE;
CREATE TABLE TEAM5_CUSTOMER
(
    CUSTOMER_ID INT NOT NULL,
    LOCATION    VARCHAR(128),
    GENDER      VARCHAR(32),
    NATIONALITY VARCHAR(128),
    PRIMARY KEY (CUSTOMER_ID)
);
grant all on "CAM13052".TEAM5_CUSTOMER to "ETG16101","SES14019","PRT15101" with grant option;

DROP TABLE INVENTORY CASCADE CONSTRAINTS PURGE;
CREATE TABLE INVENTORY
(
    PRODUCT_ID  INT NOT NULL,
    PRICE       DECIMAL(20,2),
    QUANTITY    INT,
    PRIMARY KEY (PRODUCT_ID)
);
grant all on "CAM13052".INVENTORY to "ETG16101","SES14019","PRT15101" with grant option;

DROP TABLE WAREHOUSE CASCADE CONSTRAINTS PURGE;
CREATE TABLE WAREHOUSE
(
    WAREHOUSE_ID        INT NOT NULL,
    ADDRESS             VARCHAR(255),
    STORAGE_CAPACITY    INT,
    PRIMARY KEY         (WAREHOUSE_ID)
);
grant all on "CAM13052".WAREHOUSE to "ETG16101","SES14019","PRT15101" with grant option;

DROP TABLE SUPPLIER CASCADE CONSTRAINTS PURGE;
CREATE TABLE SUPPLIER
(
    SUPPLIER_ID INT NOT NULL,
    ADDRESS     VARCHAR(255),
    NAME        VARCHAR(32),
    PRIMARY KEY (SUPPLIER_ID)
);
grant all on "CAM13052".SUPPLIER to "ETG16101","SES14019","PRT15101" with grant option;

DROP TABLE PURCHASE CASCADE CONSTRAINTS PURGE;
CREATE TABLE PURCHASE
(
    SUPPLIER_ID     INT NOT NULL,
    PRODUCT_ID      INT NOT NULL,
    TIME_PURCHASED  TIMESTAMP NOT NULL,
    QUANTITY        INT,
    COST            DECIMAL(20,2),
    FOREIGN KEY     (SUPPLIER_ID) REFERENCES SUPPLIER  (SUPPLIER_ID),
    FOREIGN KEY     (PRODUCT_ID ) REFERENCES INVENTORY (PRODUCT_ID),
    PRIMARY KEY     (SUPPLIER_ID, PRODUCT_ID, TIME_PURCHASED)
    
);
grant all on "CAM13052".PURCHASE to "ETG16101","SES14019","PRT15101" with grant option;

DROP TABLE REPAIR CASCADE CONSTRAINTS PURGE;
CREATE TABLE REPAIR
(
    PRODUCT_ID      INT NOT NULL,
    EMPLOYEE_ID     INT NOT NULL,
    TIME_REPAIRED   TIMESTAMP NOT NULL,
    PARTS_USED      INT,
    COST            DECIMAL(20,2),
    FOREIGN KEY     (EMPLOYEE_ID) REFERENCES TEAM5_EMPLOYEES(EMPLOYEE_ID),
    FOREIGN KEY     (PRODUCT_ID)  REFERENCES INVENTORY(PRODUCT_ID),
    PRIMARY KEY     (PRODUCT_ID,EMPLOYEE_ID,TIME_REPAIRED)
    
);
grant all on "CAM13052".REPAIR to "ETG16101","SES14019","PRT15101" with grant option;

DROP TABLE SALE CASCADE CONSTRAINTS PURGE;
CREATE TABLE SALE
(
    CUSTOMER_ID INT NOT NULL,
    PRODUCT_ID  INT NOT NULL,
    TIME_SOLD   TIMESTAMP NOT NULL,
    SALE_PRICE  DECIMAL(20,2),
    PROFIT      DECIMAL(20,2),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES TEAM5_CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (PRODUCT_ID)  REFERENCES INVENTORY(PRODUCT_ID),
    PRIMARY KEY (CUSTOMER_ID,PRODUCT_ID,TIME_SOLD)
);
grant all on "CAM13052".SALE to "ETG16101","SES14019","PRT15101" with grant option;